-- Schema reference for the "core" and "epdg" schemas.
-- Generated by introspecting the live database (information_schema / pg_catalog) —
-- this reflects the actual current state, not a hand-reassembly of the migration history.
-- Generated: 2026-07-02T23:18:48.834Z


-- ============================================================
-- SCHEMA: core
-- ============================================================

CREATE SCHEMA IF NOT EXISTS core;

-- --- Enum types ---
CREATE TYPE core.admin_role AS ENUM ('admin', 'super_admin');
CREATE TYPE core.user_role AS ENUM ('admin', 'company', 'intern', 'school');

-- --- Table: core.branches ---
CREATE TABLE core.branches (
    id                       INTEGER NOT NULL DEFAULT nextval('core.branches_id_seq'::regclass),
    code                     VARCHAR(30) NOT NULL,
    name                     VARCHAR(100) NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE core.branches ADD CONSTRAINT branches_code_key UNIQUE (code);


-- --- Table: core.user_branch_roles ---
CREATE TABLE core.user_branch_roles (
    id                       INTEGER NOT NULL DEFAULT nextval('core.user_branch_roles_id_seq'::regclass),
    user_id                  INTEGER NOT NULL,
    branch_id                INTEGER NOT NULL,
    role_name                core.user_role NOT NULL,
    admin_role               core.admin_role,
    rejection_reason         TEXT,
    created_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE core.user_branch_roles ADD CONSTRAINT user_branch_roles_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES core.branches(id);
ALTER TABLE core.user_branch_roles ADD CONSTRAINT user_branch_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES core.users(id);
ALTER TABLE core.user_branch_roles ADD CONSTRAINT user_branch_roles_user_id_branch_id_key UNIQUE (user_id, branch_id);

CREATE INDEX idx_user_branch_roles_branch_id ON core.user_branch_roles USING btree (branch_id);
CREATE INDEX idx_user_branch_roles_user_id ON core.user_branch_roles USING btree (user_id);


-- --- Table: core.users ---
CREATE TABLE core.users (
    id                       INTEGER NOT NULL DEFAULT nextval('core.users_id_seq'::regclass),
    email                    VARCHAR(150) NOT NULL,
    name                     VARCHAR(100) NOT NULL,
    password                 VARCHAR(255) NOT NULL,
    is_verified              BOOLEAN DEFAULT false,
    verification_token       VARCHAR(255),
    token_expires_at         TIMESTAMP WITHOUT TIME ZONE,
    last_login_at            TIMESTAMP WITHOUT TIME ZONE,
    created_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at               TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX core_users_email_unique_active ON core.users USING btree (email) WHERE (deleted_at IS NULL);



-- ============================================================
-- SCHEMA: epdg
-- ============================================================

CREATE SCHEMA IF NOT EXISTS epdg;

-- --- Enum types ---
CREATE TYPE epdg.admin_role AS ENUM ('admin', 'super_admin');
CREATE TYPE epdg.application_status AS ENUM ('pending', 'shortlisted', 'accepted', 'rejected');
CREATE TYPE epdg.internship_slot_status AS ENUM ('draft', 'open', 'closed', 'filled');
CREATE TYPE epdg.placement_status AS ENUM ('active', 'completed', 'terminated', 'on_hold');
CREATE TYPE epdg.school_type AS ENUM ('university', 'college', 'polytechnic', 'tvet');
CREATE TYPE epdg.submission_status AS ENUM ('submitted', 'under_review', 'approved', 'rejected');
CREATE TYPE epdg.task_priority AS ENUM ('low', 'normal', 'urgent');
CREATE TYPE epdg.task_status AS ENUM ('pending', 'in_progress', 'review', 'done');
CREATE TYPE epdg.user_role AS ENUM ('admin', 'company', 'intern', 'school');

-- --- Table: epdg.admins ---
CREATE TABLE epdg.admins (
    id                       INTEGER NOT NULL DEFAULT nextval('admins_id_seq'::regclass),
    user_id                  INTEGER NOT NULL,
    admin_role               epdg.admin_role NOT NULL DEFAULT 'admin'::admin_role,
    is_mentor                BOOLEAN DEFAULT false,
    department               VARCHAR(100),
    permissions              JSONB,
    created_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    max_capacity             INTEGER DEFAULT 3,
    force_password_change    BOOLEAN DEFAULT false,
    admin_type               VARCHAR(30) NOT NULL DEFAULT 'general'::character varying,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.admins ADD CONSTRAINT admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

CREATE INDEX idx_admins_admin_type ON epdg.admins USING btree (admin_type);
CREATE UNIQUE INDEX idx_admins_user_id ON epdg.admins USING btree (user_id);


-- --- Table: epdg.announcements ---
CREATE TABLE epdg.announcements (
    id                       INTEGER NOT NULL DEFAULT nextval('announcements_id_seq'::regclass),
    title                    VARCHAR(200) NOT NULL,
    body                     TEXT NOT NULL,
    audience                 VARCHAR(20) NOT NULL DEFAULT 'all'::character varying,
    created_by               INTEGER,
    created_at               TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    deleted_at               TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.announcements ADD CONSTRAINT announcements_audience_check CHECK (((audience)::text = ANY ((ARRAY['all'::character varying, 'intern'::character varying, 'company'::character varying, 'school'::character varying, 'admin'::character varying])::text[])));
ALTER TABLE epdg.announcements ADD CONSTRAINT announcements_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);

CREATE INDEX idx_announcements_audience ON epdg.announcements USING btree (audience);


-- --- Table: epdg.applications ---
CREATE TABLE epdg.applications (
    id                       INTEGER NOT NULL DEFAULT nextval('applications_id_seq'::regclass),
    intern_id                INTEGER NOT NULL,
    slot_id                  INTEGER NOT NULL,
    cover_letter             TEXT,
    status                   epdg.application_status DEFAULT 'pending'::application_status,
    company_notes            TEXT,
    applied_at               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    reviewed_at              TIMESTAMP WITH TIME ZONE,
    reviewed_by              INTEGER,
    extracted_skills         JSONB,
    cv_text_snapshot         TEXT,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.applications ADD CONSTRAINT applications_intern_id_fkey FOREIGN KEY (intern_id) REFERENCES intern_profiles(id) ON DELETE CASCADE;
ALTER TABLE epdg.applications ADD CONSTRAINT applications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE epdg.applications ADD CONSTRAINT applications_slot_id_fkey FOREIGN KEY (slot_id) REFERENCES internship_slots(id) ON DELETE CASCADE;
ALTER TABLE epdg.applications ADD CONSTRAINT applications_intern_id_slot_id_key UNIQUE (intern_id, slot_id);

CREATE INDEX idx_applications_intern_id ON epdg.applications USING btree (intern_id);
CREATE INDEX idx_applications_reviewed_by ON epdg.applications USING btree (reviewed_by);
CREATE INDEX idx_applications_slot_id ON epdg.applications USING btree (slot_id);
CREATE INDEX idx_applications_status ON epdg.applications USING btree (status);


-- --- Table: epdg.audit_log ---
CREATE TABLE epdg.audit_log (
    id                       INTEGER NOT NULL DEFAULT nextval('audit_log_id_seq'::regclass),
    admin_id                 INTEGER,
    action                   VARCHAR(100) NOT NULL,
    target_type              VARCHAR(50),
    target_id                VARCHAR(100),
    metadata                 JSONB,
    created_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.audit_log ADD CONSTRAINT audit_log_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX idx_audit_log_admin_id ON epdg.audit_log USING btree (admin_id);
CREATE INDEX idx_audit_log_created_at ON epdg.audit_log USING btree (created_at DESC);


-- --- Table: epdg.badge_awards ---
CREATE TABLE epdg.badge_awards (
    id                       INTEGER NOT NULL DEFAULT nextval('badge_awards_id_seq'::regclass),
    badge_id                 INTEGER NOT NULL,
    user_id                  INTEGER NOT NULL,
    awarded_by               INTEGER,
    awarded_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.badge_awards ADD CONSTRAINT badge_awards_awarded_by_fkey FOREIGN KEY (awarded_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE epdg.badge_awards ADD CONSTRAINT badge_awards_badge_id_fkey FOREIGN KEY (badge_id) REFERENCES badges(id) ON DELETE CASCADE;
ALTER TABLE epdg.badge_awards ADD CONSTRAINT badge_awards_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;


-- --- Table: epdg.badges ---
CREATE TABLE epdg.badges (
    id                       INTEGER NOT NULL DEFAULT nextval('badges_id_seq'::regclass),
    name                     VARCHAR(100) NOT NULL,
    emoji                    VARCHAR(10) NOT NULL,
    description              TEXT,
    created_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.badges ADD CONSTRAINT badges_name_key UNIQUE (name);


-- --- Table: epdg.career_experiences ---
CREATE TABLE epdg.career_experiences (
    id                       INTEGER NOT NULL DEFAULT nextval('career_experiences_id_seq'::regclass),
    career_file_id           INTEGER NOT NULL,
    title                    VARCHAR(255) NOT NULL,
    organization             VARCHAR(255),
    start_date               DATE,
    end_date                 DATE,
    is_current               BOOLEAN NOT NULL DEFAULT false,
    description              TEXT,
    source                   VARCHAR(20) NOT NULL DEFAULT 'manual'::character varying,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

ALTER TABLE epdg.career_experiences ADD CONSTRAINT career_experiences_source_check CHECK (((source)::text = ANY ((ARRAY['manual'::character varying, 'platform'::character varying])::text[])));
ALTER TABLE epdg.career_experiences ADD CONSTRAINT career_experiences_career_file_id_fkey FOREIGN KEY (career_file_id) REFERENCES career_files(id) ON DELETE CASCADE;


-- --- Table: epdg.career_files ---
CREATE TABLE epdg.career_files (
    id                       INTEGER NOT NULL DEFAULT nextval('career_files_id_seq'::regclass),
    intern_profile_id        INTEGER NOT NULL,
    slug                     VARCHAR(120),
    headline                 VARCHAR(255),
    summary                  TEXT,
    readiness_score          INTEGER NOT NULL DEFAULT 0,
    readiness_tier           VARCHAR(30) NOT NULL DEFAULT 'not_ready'::character varying,
    mentor_approved_tier     BOOLEAN NOT NULL DEFAULT false,
    is_public                BOOLEAN NOT NULL DEFAULT false,
    last_auto_populated_at   TIMESTAMP WITH TIME ZONE,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

ALTER TABLE epdg.career_files ADD CONSTRAINT career_files_readiness_score_check CHECK (((readiness_score >= 0) AND (readiness_score <= 100)));
ALTER TABLE epdg.career_files ADD CONSTRAINT career_files_readiness_tier_check CHECK (((readiness_tier)::text = ANY ((ARRAY['not_ready'::character varying, 'developing'::character varying, 'internship_ready'::character varying, 'internship_ready_plus'::character varying, 'employer_ready'::character varying])::text[])));
ALTER TABLE epdg.career_files ADD CONSTRAINT career_files_intern_profile_id_fkey FOREIGN KEY (intern_profile_id) REFERENCES intern_profiles(id) ON DELETE CASCADE;
ALTER TABLE epdg.career_files ADD CONSTRAINT career_files_intern_profile_id_key UNIQUE (intern_profile_id);
ALTER TABLE epdg.career_files ADD CONSTRAINT career_files_slug_key UNIQUE (slug);

CREATE INDEX idx_career_files_intern_profile ON epdg.career_files USING btree (intern_profile_id);
CREATE INDEX idx_career_files_slug ON epdg.career_files USING btree (slug);
CREATE INDEX idx_career_files_tier ON epdg.career_files USING btree (readiness_tier);


-- --- Table: epdg.career_projects ---
CREATE TABLE epdg.career_projects (
    id                       INTEGER NOT NULL DEFAULT nextval('career_projects_id_seq'::regclass),
    career_file_id           INTEGER NOT NULL,
    title                    VARCHAR(255) NOT NULL,
    description              TEXT,
    technologies             text[] DEFAULT '{}'::text[],
    url                      TEXT,
    source                   VARCHAR(30) NOT NULL DEFAULT 'manual'::character varying,
    source_ref_id            INTEGER,
    verified                 BOOLEAN NOT NULL DEFAULT false,
    mentor_signed            BOOLEAN NOT NULL DEFAULT false,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

ALTER TABLE epdg.career_projects ADD CONSTRAINT career_projects_source_check CHECK (((source)::text = ANY ((ARRAY['manual'::character varying, 'module_completion'::character varying, 'submission'::character varying, 'portfolio'::character varying])::text[])));
ALTER TABLE epdg.career_projects ADD CONSTRAINT career_projects_career_file_id_fkey FOREIGN KEY (career_file_id) REFERENCES career_files(id) ON DELETE CASCADE;

CREATE INDEX idx_career_projects_file ON epdg.career_projects USING btree (career_file_id);
CREATE UNIQUE INDEX idx_career_projects_platform_dedup ON epdg.career_projects USING btree (career_file_id, source, source_ref_id) WHERE (source_ref_id IS NOT NULL);


-- --- Table: epdg.career_skills ---
CREATE TABLE epdg.career_skills (
    id                       INTEGER NOT NULL DEFAULT nextval('career_skills_id_seq'::regclass),
    career_file_id           INTEGER NOT NULL,
    skill_name               VARCHAR(100) NOT NULL,
    category                 VARCHAR(50),
    source                   VARCHAR(30) NOT NULL DEFAULT 'self_reported'::character varying,
    proficiency              VARCHAR(20) NOT NULL DEFAULT 'beginner'::character varying,
    endorsed_by              INTEGER,
    endorsed_at              TIMESTAMP WITH TIME ZONE,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

ALTER TABLE epdg.career_skills ADD CONSTRAINT career_skills_proficiency_check CHECK (((proficiency)::text = ANY ((ARRAY['beginner'::character varying, 'intermediate'::character varying, 'advanced'::character varying])::text[])));
ALTER TABLE epdg.career_skills ADD CONSTRAINT career_skills_source_check CHECK (((source)::text = ANY ((ARRAY['self_reported'::character varying, 'extracted_cv'::character varying, 'platform_activity'::character varying, 'mentor_endorsed'::character varying])::text[])));
ALTER TABLE epdg.career_skills ADD CONSTRAINT career_skills_career_file_id_fkey FOREIGN KEY (career_file_id) REFERENCES career_files(id) ON DELETE CASCADE;
ALTER TABLE epdg.career_skills ADD CONSTRAINT career_skills_endorsed_by_fkey FOREIGN KEY (endorsed_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE epdg.career_skills ADD CONSTRAINT career_skills_career_file_id_skill_name_key UNIQUE (career_file_id, skill_name);

CREATE INDEX idx_career_skills_file ON epdg.career_skills USING btree (career_file_id);


-- --- Table: epdg.certificate_templates ---
CREATE TABLE epdg.certificate_templates (
    id                       INTEGER NOT NULL DEFAULT nextval('certificate_templates_id_seq'::regclass),
    name                     VARCHAR(100) NOT NULL,
    department               VARCHAR(100),
    background_image_url     TEXT,
    field_positions          JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);


-- --- Table: epdg.certificates ---
CREATE TABLE epdg.certificates (
    id                       UUID NOT NULL DEFAULT gen_random_uuid(),
    certificate_number       VARCHAR(50) NOT NULL,
    intern_id                INTEGER NOT NULL,
    intern_name_snapshot     VARCHAR(200) NOT NULL,
    department_snapshot      VARCHAR(100),
    program_name             VARCHAR(200) NOT NULL,
    issue_date               DATE NOT NULL DEFAULT CURRENT_DATE,
    issued_by                INTEGER NOT NULL,
    template_id              INTEGER,
    pdf_url                  TEXT,
    integrity_hash           VARCHAR(64) NOT NULL,
    status                   VARCHAR(20) NOT NULL DEFAULT 'active'::character varying,
    created_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.certificates ADD CONSTRAINT certificates_status_check CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'revoked'::character varying])::text[])));
ALTER TABLE epdg.certificates ADD CONSTRAINT certificates_intern_id_fkey FOREIGN KEY (intern_id) REFERENCES users(id);
ALTER TABLE epdg.certificates ADD CONSTRAINT certificates_issued_by_fkey FOREIGN KEY (issued_by) REFERENCES users(id);
ALTER TABLE epdg.certificates ADD CONSTRAINT certificates_template_id_fkey FOREIGN KEY (template_id) REFERENCES certificate_templates(id);
ALTER TABLE epdg.certificates ADD CONSTRAINT certificates_certificate_number_key UNIQUE (certificate_number);


-- --- Table: epdg.companies ---
CREATE TABLE epdg.companies (
    id                       INTEGER NOT NULL DEFAULT nextval('companies_id_seq'::regclass),
    user_id                  INTEGER NOT NULL,
    company_name             VARCHAR(150) NOT NULL,
    email                    VARCHAR(150),
    country                  VARCHAR(100),
    county                   VARCHAR(100),
    industry                 VARCHAR(100),
    number_of_employees      INTEGER,
    registration_number      VARCHAR(100),
    website                  VARCHAR(255),
    logo_url                 VARCHAR(500),
    description              TEXT,
    contact_person           VARCHAR(100),
    contact_phone            VARCHAR(20),
    is_verified              BOOLEAN DEFAULT false,
    is_approved              BOOLEAN DEFAULT false,
    approved_at              TIMESTAMP WITH TIME ZONE,
    approved_by              INTEGER,
    created_at               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at               TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.companies ADD CONSTRAINT companies_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE epdg.companies ADD CONSTRAINT companies_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

CREATE INDEX idx_companies_approved_by ON epdg.companies USING btree (approved_by);
CREATE INDEX idx_companies_user_id ON epdg.companies USING btree (user_id);


-- --- Table: epdg.feedback ---
CREATE TABLE epdg.feedback (
    id                       INTEGER NOT NULL DEFAULT nextval('feedback_id_seq'::regclass),
    placement_id             INTEGER NOT NULL,
    given_by                 INTEGER NOT NULL,
    type                     VARCHAR(30) NOT NULL,
    rating                   SMALLINT NOT NULL,
    comment                  TEXT,
    is_anonymous             BOOLEAN DEFAULT false,
    week_number              INTEGER,
    created_at               TIMESTAMP WITH TIME ZONE DEFAULT now(),
    target_user_id           INTEGER,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.feedback ADD CONSTRAINT feedback_rating_check CHECK (((rating >= 1) AND (rating <= 5)));
ALTER TABLE epdg.feedback ADD CONSTRAINT feedback_type_check CHECK (((type)::text = ANY ((ARRAY['intern_to_program'::character varying, 'mentor_to_intern'::character varying, 'intern_to_mentor'::character varying])::text[])));
ALTER TABLE epdg.feedback ADD CONSTRAINT feedback_given_by_fkey FOREIGN KEY (given_by) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE epdg.feedback ADD CONSTRAINT feedback_placement_id_fkey FOREIGN KEY (placement_id) REFERENCES placements(id) ON DELETE CASCADE;
ALTER TABLE epdg.feedback ADD CONSTRAINT feedback_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX idx_feedback_placement_id ON epdg.feedback USING btree (placement_id);


-- --- Table: epdg.intern_level_progress ---
CREATE TABLE epdg.intern_level_progress (
    id                       INTEGER NOT NULL DEFAULT nextval('intern_level_progress_id_seq'::regclass),
    intern_id                INTEGER NOT NULL,
    track_id                 INTEGER NOT NULL,
    current_level            VARCHAR(20) NOT NULL DEFAULT 'beginner'::character varying,
    level_started_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    level_up_requested_at    TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.intern_level_progress ADD CONSTRAINT intern_level_progress_current_level_check CHECK (((current_level)::text = ANY ((ARRAY['beginner'::character varying, 'intermediate'::character varying, 'advanced'::character varying])::text[])));
ALTER TABLE epdg.intern_level_progress ADD CONSTRAINT intern_level_progress_intern_id_fkey FOREIGN KEY (intern_id) REFERENCES intern_profiles(id) ON DELETE CASCADE;
ALTER TABLE epdg.intern_level_progress ADD CONSTRAINT intern_level_progress_track_id_fkey FOREIGN KEY (track_id) REFERENCES tracks(id);
ALTER TABLE epdg.intern_level_progress ADD CONSTRAINT intern_level_progress_intern_id_track_id_key UNIQUE (intern_id, track_id);

CREATE INDEX idx_intern_level_progress_intern ON epdg.intern_level_progress USING btree (intern_id);


-- --- Table: epdg.intern_profiles ---
CREATE TABLE epdg.intern_profiles (
    id                       INTEGER NOT NULL DEFAULT nextval('intern_profiles_id_seq'::regclass),
    user_id                  INTEGER NOT NULL,
    school_id                INTEGER,
    course                   VARCHAR(150),
    year_of_study            SMALLINT,
    cv_url                   VARCHAR(500),
    skills                   JSONB,
    bio                      TEXT,
    availability_start       DATE,
    availability_end         DATE,
    nda_signed               BOOLEAN DEFAULT false,
    disclaimer_accepted      BOOLEAN DEFAULT false,
    onboarding_complete      BOOLEAN DEFAULT false,
    created_at               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_approved              BOOLEAN NOT NULL DEFAULT false,
    approved_at              TIMESTAMP WITH TIME ZONE,
    approved_by              INTEGER,
    rejection_reason         TEXT,
    contact_phone            VARCHAR(20),
    department               VARCHAR(100),
    mentor_name              VARCHAR(100),
    track                    VARCHAR(100),
    onboarding_step          INTEGER NOT NULL DEFAULT 1,
    profile_photo            VARCHAR(500),
    linkedin_url             VARCHAR(500),
    github_url               VARCHAR(500),
    portfolio_url            VARCHAR(500),
    country                  VARCHAR(100),
    city                     VARCHAR(100),
    cover_letter             TEXT,
    onboarding_status        VARCHAR(30) NOT NULL DEFAULT 'pending_approval'::character varying,
    mentor_id                INTEGER,
    track_confirmed_at       TIMESTAMP WITH TIME ZONE,
    discovery_problem        TEXT,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.intern_profiles ADD CONSTRAINT intern_profiles_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES users(id);
ALTER TABLE epdg.intern_profiles ADD CONSTRAINT intern_profiles_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE epdg.intern_profiles ADD CONSTRAINT intern_profiles_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL;
ALTER TABLE epdg.intern_profiles ADD CONSTRAINT intern_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

CREATE INDEX idx_intern_profiles_approved ON epdg.intern_profiles USING btree (is_approved);
CREATE INDEX idx_intern_profiles_school_id ON epdg.intern_profiles USING btree (school_id);
CREATE INDEX idx_intern_profiles_user_id ON epdg.intern_profiles USING btree (user_id);


-- --- Table: epdg.intern_roadmap_progress ---
CREATE TABLE epdg.intern_roadmap_progress (
    id                       INTEGER NOT NULL DEFAULT nextval('intern_roadmap_progress_id_seq'::regclass),
    intern_id                INTEGER NOT NULL,
    week_id                  INTEGER NOT NULL,
    status                   VARCHAR(20) NOT NULL DEFAULT 'locked'::character varying,
    completed_at             TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.intern_roadmap_progress ADD CONSTRAINT intern_roadmap_progress_intern_id_fkey FOREIGN KEY (intern_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE epdg.intern_roadmap_progress ADD CONSTRAINT intern_roadmap_progress_week_id_fkey FOREIGN KEY (week_id) REFERENCES roadmap_weeks(id) ON DELETE CASCADE;
ALTER TABLE epdg.intern_roadmap_progress ADD CONSTRAINT intern_roadmap_progress_intern_id_week_id_key UNIQUE (intern_id, week_id);

CREATE INDEX idx_intern_roadmap_intern_id ON epdg.intern_roadmap_progress USING btree (intern_id);


-- --- Table: epdg.intern_skills ---
CREATE TABLE epdg.intern_skills (
    id                       INTEGER NOT NULL DEFAULT nextval('intern_skills_id_seq'::regclass),
    intern_id                INTEGER NOT NULL,
    skill_name               VARCHAR(100) NOT NULL,
    proficiency              SMALLINT NOT NULL DEFAULT 0,
    updated_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.intern_skills ADD CONSTRAINT intern_skills_proficiency_check CHECK (((proficiency >= 0) AND (proficiency <= 100)));
ALTER TABLE epdg.intern_skills ADD CONSTRAINT intern_skills_intern_id_fkey FOREIGN KEY (intern_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE epdg.intern_skills ADD CONSTRAINT intern_skills_intern_id_skill_name_key UNIQUE (intern_id, skill_name);

CREATE INDEX idx_intern_skills_intern_id ON epdg.intern_skills USING btree (intern_id);


-- --- Table: epdg.internship_slots ---
CREATE TABLE epdg.internship_slots (
    id                       INTEGER NOT NULL DEFAULT nextval('internship_slots_id_seq'::regclass),
    company_id               INTEGER,
    title                    VARCHAR(200) NOT NULL,
    department               VARCHAR(100),
    description              TEXT,
    requirements             TEXT,
    skills_required          JSONB,
    slots_available          INTEGER DEFAULT 1,
    slots_filled             INTEGER DEFAULT 0,
    duration_weeks           INTEGER,
    stipend                  NUMERIC(10,2),
    is_remote                BOOLEAN DEFAULT false,
    county                   VARCHAR(100),
    deadline                 DATE,
    status                   epdg.internship_slot_status DEFAULT 'draft'::internship_slot_status,
    created_at               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at               TIMESTAMP WITH TIME ZONE,
    created_by               INTEGER,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.internship_slots ADD CONSTRAINT internship_slots_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE epdg.internship_slots ADD CONSTRAINT internship_slots_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX idx_internship_slots_company_id ON epdg.internship_slots USING btree (company_id);
CREATE INDEX idx_internship_slots_status ON epdg.internship_slots USING btree (status);


-- --- Table: epdg.mentor_sessions ---
CREATE TABLE epdg.mentor_sessions (
    id                       INTEGER NOT NULL DEFAULT nextval('mentor_sessions_id_seq'::regclass),
    placement_id             INTEGER NOT NULL,
    mentor_id                INTEGER NOT NULL,
    intern_id                INTEGER NOT NULL,
    scheduled_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status                   VARCHAR(20) NOT NULL DEFAULT 'pending'::character varying,
    notes                    TEXT,
    intern_rating            SMALLINT,
    mentor_notes             TEXT,
    created_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.mentor_sessions ADD CONSTRAINT mentor_sessions_intern_id_fkey FOREIGN KEY (intern_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE epdg.mentor_sessions ADD CONSTRAINT mentor_sessions_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE epdg.mentor_sessions ADD CONSTRAINT mentor_sessions_placement_id_fkey FOREIGN KEY (placement_id) REFERENCES placements(id) ON DELETE CASCADE;

CREATE INDEX idx_mentor_sessions_intern_id ON epdg.mentor_sessions USING btree (intern_id);
CREATE INDEX idx_mentor_sessions_mentor_id ON epdg.mentor_sessions USING btree (mentor_id);
CREATE INDEX idx_mentor_sessions_placement ON epdg.mentor_sessions USING btree (placement_id);


-- --- Table: epdg.milestones ---
CREATE TABLE epdg.milestones (
    id                       INTEGER NOT NULL DEFAULT nextval('milestones_id_seq'::regclass),
    placement_id             INTEGER NOT NULL,
    title                    VARCHAR(200) NOT NULL,
    description              TEXT,
    due_week                 INTEGER NOT NULL,
    is_completed             BOOLEAN DEFAULT false,
    completed_by             INTEGER,
    completed_at             TIMESTAMP WITH TIME ZONE,
    created_at               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.milestones ADD CONSTRAINT milestones_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE epdg.milestones ADD CONSTRAINT milestones_placement_id_fkey FOREIGN KEY (placement_id) REFERENCES placements(id) ON DELETE CASCADE;

CREATE INDEX idx_milestones_completed_by ON epdg.milestones USING btree (completed_by);
CREATE INDEX idx_milestones_placement_id ON epdg.milestones USING btree (placement_id);


-- --- Table: epdg.module_completions ---
CREATE TABLE epdg.module_completions (
    id                       INTEGER NOT NULL DEFAULT nextval('module_completions_id_seq'::regclass),
    intern_id                INTEGER NOT NULL,
    module_id                INTEGER NOT NULL,
    completed_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    mentor_signed            BOOLEAN NOT NULL DEFAULT false,
    mentor_id                INTEGER,
    mentor_signed_at         TIMESTAMP WITH TIME ZONE,
    artifact_url             TEXT,
    notes                    TEXT,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.module_completions ADD CONSTRAINT module_completions_intern_id_fkey FOREIGN KEY (intern_id) REFERENCES intern_profiles(id) ON DELETE CASCADE;
ALTER TABLE epdg.module_completions ADD CONSTRAINT module_completions_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE epdg.module_completions ADD CONSTRAINT module_completions_module_id_fkey FOREIGN KEY (module_id) REFERENCES roadmap_modules(id);
ALTER TABLE epdg.module_completions ADD CONSTRAINT module_completions_intern_id_module_id_key UNIQUE (intern_id, module_id);

CREATE INDEX idx_module_completions_intern_id ON epdg.module_completions USING btree (intern_id);


-- --- Table: epdg.onboarding_agreements ---
CREATE TABLE epdg.onboarding_agreements (
    id                       INTEGER NOT NULL DEFAULT nextval('onboarding_agreements_id_seq'::regclass),
    intern_id                INTEGER NOT NULL,
    agreement_type           VARCHAR(30) NOT NULL,
    agreed_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    ip_address               VARCHAR(45),
    user_agent               TEXT,
    agreement_text           TEXT NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.onboarding_agreements ADD CONSTRAINT onboarding_agreements_agreement_type_check CHECK (((agreement_type)::text = ANY ((ARRAY['nda'::character varying, 'disclaimer'::character varying])::text[])));
ALTER TABLE epdg.onboarding_agreements ADD CONSTRAINT onboarding_agreements_intern_id_fkey FOREIGN KEY (intern_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE epdg.onboarding_agreements ADD CONSTRAINT onboarding_agreements_intern_id_agreement_type_key UNIQUE (intern_id, agreement_type);

CREATE INDEX idx_onboarding_agreements_intern ON epdg.onboarding_agreements USING btree (intern_id);


-- --- Table: epdg.opportunities ---
CREATE TABLE epdg.opportunities (
    id                       INTEGER NOT NULL DEFAULT nextval('opportunities_id_seq'::regclass),
    type                     VARCHAR(10) NOT NULL DEFAULT 'gig'::character varying,
    title                    VARCHAR(200) NOT NULL,
    company_id               INTEGER,
    department               VARCHAR(100),
    description              TEXT,
    requirements             TEXT,
    skills_required          JSONB,
    compensation             VARCHAR(100),
    duration                 VARCHAR(100),
    is_remote                BOOLEAN NOT NULL DEFAULT false,
    county                   VARCHAR(100),
    deadline                 DATE,
    status                   VARCHAR(20) NOT NULL DEFAULT 'open'::character varying,
    posted_by                INTEGER,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    deleted_at               TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.opportunities ADD CONSTRAINT opportunities_status_check CHECK (((status)::text = ANY ((ARRAY['open'::character varying, 'closed'::character varying, 'filled'::character varying])::text[])));
ALTER TABLE epdg.opportunities ADD CONSTRAINT opportunities_type_check CHECK (((type)::text = ANY ((ARRAY['gig'::character varying, 'job'::character varying])::text[])));
ALTER TABLE epdg.opportunities ADD CONSTRAINT opportunities_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
ALTER TABLE epdg.opportunities ADD CONSTRAINT opportunities_posted_by_fkey FOREIGN KEY (posted_by) REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX idx_opportunities_status ON epdg.opportunities USING btree (status);
CREATE INDEX idx_opportunities_type ON epdg.opportunities USING btree (type);


-- --- Table: epdg.opportunity_applications ---
CREATE TABLE epdg.opportunity_applications (
    id                       INTEGER NOT NULL DEFAULT nextval('opportunity_applications_id_seq'::regclass),
    intern_id                INTEGER NOT NULL,
    opportunity_id           INTEGER NOT NULL,
    cover_letter             TEXT,
    status                   VARCHAR(20) NOT NULL DEFAULT 'pending'::character varying,
    applied_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    reviewed_at              TIMESTAMP WITH TIME ZONE,
    reviewed_by              INTEGER,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.opportunity_applications ADD CONSTRAINT opportunity_applications_status_check CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'shortlisted'::character varying, 'accepted'::character varying, 'rejected'::character varying])::text[])));
ALTER TABLE epdg.opportunity_applications ADD CONSTRAINT opportunity_applications_intern_id_fkey FOREIGN KEY (intern_id) REFERENCES intern_profiles(id) ON DELETE CASCADE;
ALTER TABLE epdg.opportunity_applications ADD CONSTRAINT opportunity_applications_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE;
ALTER TABLE epdg.opportunity_applications ADD CONSTRAINT opportunity_applications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE epdg.opportunity_applications ADD CONSTRAINT opportunity_applications_intern_id_opportunity_id_key UNIQUE (intern_id, opportunity_id);

CREATE INDEX idx_opp_apps_intern_id ON epdg.opportunity_applications USING btree (intern_id);
CREATE INDEX idx_opp_apps_opp_id ON epdg.opportunity_applications USING btree (opportunity_id);


-- --- Table: epdg.placements ---
CREATE TABLE epdg.placements (
    id                       INTEGER NOT NULL DEFAULT nextval('placements_id_seq'::regclass),
    application_id           INTEGER NOT NULL,
    intern_id                INTEGER NOT NULL,
    company_id               INTEGER NOT NULL,
    school_id                INTEGER,
    slot_id                  INTEGER NOT NULL,
    mentor_id                INTEGER,
    start_date               DATE NOT NULL,
    end_date                 DATE NOT NULL,
    status                   epdg.placement_status DEFAULT 'active'::placement_status,
    termination_reason       TEXT,
    completed_at             TIMESTAMP WITH TIME ZONE,
    created_at               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.placements ADD CONSTRAINT placements_application_id_fkey FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE;
ALTER TABLE epdg.placements ADD CONSTRAINT placements_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE epdg.placements ADD CONSTRAINT placements_intern_id_fkey FOREIGN KEY (intern_id) REFERENCES intern_profiles(id) ON DELETE CASCADE;
ALTER TABLE epdg.placements ADD CONSTRAINT placements_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE epdg.placements ADD CONSTRAINT placements_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE epdg.placements ADD CONSTRAINT placements_slot_id_fkey FOREIGN KEY (slot_id) REFERENCES internship_slots(id) ON DELETE CASCADE;
ALTER TABLE epdg.placements ADD CONSTRAINT placements_application_id_key UNIQUE (application_id);

CREATE INDEX idx_placements_company_id ON epdg.placements USING btree (company_id);
CREATE INDEX idx_placements_intern_id ON epdg.placements USING btree (intern_id);
CREATE INDEX idx_placements_mentor_id ON epdg.placements USING btree (mentor_id);
CREATE INDEX idx_placements_school_id ON epdg.placements USING btree (school_id);
CREATE INDEX idx_placements_slot_id ON epdg.placements USING btree (slot_id);
CREATE INDEX idx_placements_status ON epdg.placements USING btree (status);


-- --- Table: epdg.platform_settings ---
CREATE TABLE epdg.platform_settings (
    key                      VARCHAR(100) NOT NULL,
    value                    TEXT NOT NULL,
    updated_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (key)
);


-- --- Table: epdg.point_events ---
CREATE TABLE epdg.point_events (
    id                       INTEGER NOT NULL DEFAULT nextval('point_events_id_seq'::regclass),
    user_id                  INTEGER NOT NULL,
    action                   VARCHAR(200) NOT NULL,
    points                   INTEGER NOT NULL,
    awarded_by               INTEGER,
    created_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.point_events ADD CONSTRAINT point_events_awarded_by_fkey FOREIGN KEY (awarded_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE epdg.point_events ADD CONSTRAINT point_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;


-- --- Table: epdg.readiness_score_history ---
CREATE TABLE epdg.readiness_score_history (
    id                       INTEGER NOT NULL DEFAULT nextval('readiness_score_history_id_seq'::regclass),
    career_file_id           INTEGER NOT NULL,
    score                    INTEGER NOT NULL,
    tier                     VARCHAR(30) NOT NULL,
    breakdown                JSONB,
    snapshot_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

ALTER TABLE epdg.readiness_score_history ADD CONSTRAINT readiness_score_history_score_check CHECK (((score >= 0) AND (score <= 100)));
ALTER TABLE epdg.readiness_score_history ADD CONSTRAINT readiness_score_history_career_file_id_fkey FOREIGN KEY (career_file_id) REFERENCES career_files(id) ON DELETE CASCADE;

CREATE INDEX idx_readiness_history_file ON epdg.readiness_score_history USING btree (career_file_id, snapshot_at);


-- --- Table: epdg.resources ---
CREATE TABLE epdg.resources (
    id                       INTEGER NOT NULL DEFAULT nextval('resources_id_seq'::regclass),
    title                    VARCHAR(200) NOT NULL,
    type                     VARCHAR(30) NOT NULL,
    category                 VARCHAR(100),
    url                      VARCHAR(500) NOT NULL,
    description              TEXT,
    thumbnail_url            VARCHAR(500),
    is_featured              BOOLEAN DEFAULT false,
    views                    INTEGER DEFAULT 0,
    saves                    INTEGER DEFAULT 0,
    uploaded_by              INTEGER NOT NULL,
    created_at               TIMESTAMP WITH TIME ZONE DEFAULT now(),
    deleted_at               TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.resources ADD CONSTRAINT resources_type_check CHECK (((type)::text = ANY ((ARRAY['article'::character varying, 'video'::character varying, 'course'::character varying, 'opportunity'::character varying, 'event'::character varying, 'scholarship'::character varying])::text[])));
ALTER TABLE epdg.resources ADD CONSTRAINT resources_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE CASCADE;

CREATE INDEX idx_resources_category ON epdg.resources USING btree (category);
CREATE INDEX idx_resources_type ON epdg.resources USING btree (type);


-- --- Table: epdg.roadmap_modules ---
CREATE TABLE epdg.roadmap_modules (
    id                       INTEGER NOT NULL DEFAULT nextval('roadmap_modules_id_seq'::regclass),
    track_id                 INTEGER NOT NULL,
    level                    VARCHAR(20) NOT NULL,
    order_index              INTEGER NOT NULL,
    title                    VARCHAR(200) NOT NULL,
    objective                TEXT NOT NULL,
    artifact                 TEXT NOT NULL,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

ALTER TABLE epdg.roadmap_modules ADD CONSTRAINT roadmap_modules_level_check CHECK (((level)::text = ANY ((ARRAY['beginner'::character varying, 'intermediate'::character varying, 'advanced'::character varying])::text[])));
ALTER TABLE epdg.roadmap_modules ADD CONSTRAINT roadmap_modules_track_id_fkey FOREIGN KEY (track_id) REFERENCES tracks(id);
ALTER TABLE epdg.roadmap_modules ADD CONSTRAINT roadmap_modules_track_id_level_order_index_key UNIQUE (track_id, level, order_index);

CREATE INDEX idx_roadmap_modules_track_level ON epdg.roadmap_modules USING btree (track_id, level);


-- --- Table: epdg.roadmap_weeks ---
CREATE TABLE epdg.roadmap_weeks (
    id                       INTEGER NOT NULL DEFAULT nextval('roadmap_weeks_id_seq'::regclass),
    week_number              SMALLINT NOT NULL,
    title                    VARCHAR(200) NOT NULL,
    description              TEXT,
    skills                   text[] DEFAULT '{}'::text[],
    created_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.roadmap_weeks ADD CONSTRAINT roadmap_weeks_week_number_key UNIQUE (week_number);


-- --- Table: epdg.schools ---
CREATE TABLE epdg.schools (
    id                       INTEGER NOT NULL DEFAULT nextval('schools_id_seq'::regclass),
    user_id                  INTEGER NOT NULL,
    school_name              VARCHAR(150) NOT NULL,
    email                    VARCHAR(150),
    school_type              epdg.school_type,
    county                   VARCHAR(100),
    address                  TEXT,
    website                  VARCHAR(255),
    logo_url                 VARCHAR(500),
    contact_person           VARCHAR(100),
    contact_phone            VARCHAR(20),
    courses_offered          JSONB,
    is_verified              BOOLEAN DEFAULT false,
    is_approved              BOOLEAN DEFAULT false,
    approved_at              TIMESTAMP WITH TIME ZONE,
    approved_by              INTEGER,
    created_at               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at               TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.schools ADD CONSTRAINT schools_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE epdg.schools ADD CONSTRAINT schools_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

CREATE INDEX idx_schools_approved_by ON epdg.schools USING btree (approved_by);
CREATE INDEX idx_schools_user_id ON epdg.schools USING btree (user_id);


-- --- Table: epdg.submissions ---
CREATE TABLE epdg.submissions (
    id                       INTEGER NOT NULL DEFAULT nextval('submissions_id_seq'::regclass),
    task_id                  INTEGER NOT NULL,
    placement_id             INTEGER NOT NULL,
    intern_id                INTEGER NOT NULL,
    file_url                 VARCHAR(500) NOT NULL,
    file_name                VARCHAR(255),
    file_size_kb             INTEGER,
    notes                    TEXT,
    status                   epdg.submission_status DEFAULT 'submitted'::submission_status,
    reviewer_comment         TEXT,
    reviewed_by              INTEGER,
    submitted_at             TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    reviewed_at              TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.submissions ADD CONSTRAINT submissions_intern_id_fkey FOREIGN KEY (intern_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE epdg.submissions ADD CONSTRAINT submissions_placement_id_fkey FOREIGN KEY (placement_id) REFERENCES placements(id) ON DELETE CASCADE;
ALTER TABLE epdg.submissions ADD CONSTRAINT submissions_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE epdg.submissions ADD CONSTRAINT submissions_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE;

CREATE INDEX idx_submissions_intern_id ON epdg.submissions USING btree (intern_id);
CREATE INDEX idx_submissions_placement_id ON epdg.submissions USING btree (placement_id);
CREATE INDEX idx_submissions_reviewed_by ON epdg.submissions USING btree (reviewed_by);
CREATE INDEX idx_submissions_status ON epdg.submissions USING btree (status);
CREATE INDEX idx_submissions_task_id ON epdg.submissions USING btree (task_id);


-- --- Table: epdg.tasks ---
CREATE TABLE epdg.tasks (
    id                       INTEGER NOT NULL DEFAULT nextval('tasks_id_seq'::regclass),
    placement_id             INTEGER NOT NULL,
    assigned_by              INTEGER NOT NULL,
    title                    VARCHAR(200) NOT NULL,
    description              TEXT,
    priority                 epdg.task_priority DEFAULT 'normal'::task_priority,
    status                   epdg.task_status DEFAULT 'pending'::task_status,
    due_date                 TIMESTAMP WITH TIME ZONE NOT NULL,
    points                   INTEGER DEFAULT 10,
    created_at               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    completed_at             TIMESTAMP WITH TIME ZONE,
    deleted_at               TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id)
);

ALTER TABLE epdg.tasks ADD CONSTRAINT tasks_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE epdg.tasks ADD CONSTRAINT tasks_placement_id_fkey FOREIGN KEY (placement_id) REFERENCES placements(id) ON DELETE CASCADE;

CREATE INDEX idx_tasks_assigned_by ON epdg.tasks USING btree (assigned_by);
CREATE INDEX idx_tasks_placement_id ON epdg.tasks USING btree (placement_id);
CREATE INDEX idx_tasks_status ON epdg.tasks USING btree (status);


-- --- Table: epdg.tracks ---
CREATE TABLE epdg.tracks (
    id                       INTEGER NOT NULL DEFAULT nextval('tracks_id_seq'::regclass),
    slug                     VARCHAR(50) NOT NULL,
    name                     VARCHAR(100) NOT NULL,
    description              TEXT,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

ALTER TABLE epdg.tracks ADD CONSTRAINT tracks_slug_key UNIQUE (slug);


-- --- Table: epdg.users ---
CREATE TABLE epdg.users (
    id                       INTEGER NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    email                    VARCHAR(150) NOT NULL,
    name                     VARCHAR(100) NOT NULL,
    password                 VARCHAR(255) NOT NULL,
    role                     epdg.user_role NOT NULL,
    is_verified              BOOLEAN DEFAULT false,
    verification_token       VARCHAR(255),
    token_expires_at         TIMESTAMP WITH TIME ZONE,
    last_login_at            TIMESTAMP WITH TIME ZONE,
    created_at               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at               TIMESTAMP WITH TIME ZONE,
    rejection_reason         TEXT,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX users_email_unique_active ON epdg.users USING btree (email) WHERE (deleted_at IS NULL);


